[build]
  command = "python -m pip install -r requirements.txt"
  publish = "."
  functions = "."

[build.environment]
  PYTHON_VERSION = "3.8" # Replace with the Python version you're using

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200