[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.8.0"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200