[build]
  command = "npm run build"
  publish = "dist"
  functions = "."

[build.environment]
  PYTHON_VERSION = "3.8"  # Specify the Python version you are using

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main"
  status = 200